const routes=[['Workspace',['Home','Projects','Character Library','Scene Builder','Shot Timeline','Pose & Masks']],['Production',['Image Workspace','Video Workspace','Audio Workspace','AV Workspace','Runs','QA & Compare']],['System',['Models & Capabilities','Runtime & Workers','Assets','Settings & Admin']]];
const nav=document.querySelector('#nav');routes.forEach(([label,items])=>{const heading=document.createElement('div');heading.className='nav-label';heading.textContent=label;nav.append(heading);items.forEach(name=>{const button=document.createElement('button');button.textContent=name;button.dataset.route=name.toLowerCase().replaceAll(' ','_').replaceAll('&','and');if(name==='Runs')button.classList.add('active');button.addEventListener('click',()=>{nav.querySelectorAll('button').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.querySelector('#pageTitle').textContent=name;document.querySelector('[data-tab="live"]').click()});nav.append(button)})});
document.querySelectorAll('#modeControl button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('#modeControl button').forEach(x=>x.classList.remove('active'));button.classList.add('active')}));
const panels={live:'livePanel',builder:'builderPanel',qa:'qaPanel',lineage:'lineagePanel'};document.querySelectorAll('.tabs button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));button.classList.add('active');Object.values(panels).forEach(id=>document.querySelector('#'+id).classList.add('hidden'));document.querySelector('#'+panels[button.dataset.tab]).classList.remove('hidden')}));
document.querySelector('#newJobButton').addEventListener('click',()=>document.querySelector('[data-tab="builder"]').click());
const banner=document.querySelector('#stateBanner');function announce(text){banner.textContent=text;banner.classList.remove('hidden')}
document.querySelector('#reconnectButton').addEventListener('click',event=>{event.currentTarget.disabled=true;document.querySelector('#connectionLabel').textContent='Reconciling';announce('Projection reconnect in progress. Commands are held until freshness is restored.');setTimeout(()=>{event.currentTarget.disabled=false;document.querySelector('#connectionLabel').textContent='Ready';announce('Projection reconciled from durable controller state.')},350)});
document.querySelector('#cancelButton').addEventListener('click',event=>{event.currentTarget.disabled=true;event.currentTarget.textContent='Cancelling';announce('Cancellation command recorded. The current attempt remains visible until the worker receipt confirms termination.');document.querySelector('.dag li.running b').textContent='Cancelling'});
document.querySelector('#replayButton').addEventListener('click',()=>announce('Projection replayed from immutable controller events. No execution was submitted.'));
function validate(){const character=document.querySelector('#character').value,scene=document.querySelector('#scene').value,budget=Number(document.querySelector('#budget').value);const errors=[];if(!character)errors.push('Character package is required.');if(!scene)errors.push('Scene revision is required.');if(budget<1||budget>3)errors.push('Attempt budget must be between 1 and 3.');document.querySelector('#formError').textContent=errors.join(' ');return errors.length===0}
document.querySelector('#previewButton').addEventListener('click',()=>{if(!validate())return;const media=document.querySelector('#media').value;const steps=['Validate packages','Resolve ownership','Plan image passes'];if(media!=='image')steps.push('Plan motion');if(media==='av')steps.push('Plan audio and sync');steps.push('Create unpromoted candidate');document.querySelector('#dagPreview').innerHTML='<h3>Expected DAG</h3><ol>'+steps.map(step=>'<li>'+step+'</li>').join('')+'</ol>'});
document.querySelector('#jobForm').addEventListener('submit',event=>{event.preventDefault();if(!validate())return;announce('Controller request validated locally. Submission is unavailable until a live authenticated controller API is bound.');document.querySelector('[data-tab="live"]').click()});
