comfy_ui_main:
  base_path: C:\Comfy_UI_Main\models
  checkpoints: checkpoints
  controlnet: |
    controlnet
    t2i_adapter
  upscale_models: upscale_models
  loras: loras
  vae: vae
  embeddings: embeddings
  clip_vision: clip_vision
  text_encoders: |
    text_encoders
    clip
  diffusion_models: |
    diffusion_models
    unet
  style_models: style_models
  latent_upscale_models: latent_upscale_models
  hypernetworks: hypernetworks
  photomaker: photomaker
  model_patches: model_patches
  ipadapter: ipadapter
  animatediff_models: animatediff_models
  audio_encoders: audio_encoders
  background_removal: background_removal
  mmaudio: mmaudio
  frame_interpolation: frame_interpolation
  geometry_estimation: geometry_estimation
  optical_flow: optical_flow
  detection: detection
