#!/usr/bin/env python3
"""Compile a Wave17 body-shape correction contract.

This script creates a minimal contract JSON that can be edited or passed to
the validator before workflow patching.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def build_contract(args: argparse.Namespace) -> dict[str, Any]:
    source = Path(args.source_image)
    source_hash = args.source_sha256 or (sha256_file(source) if source.exists() else "REPLACE_WITH_SOURCE_SHA256")
    regions = [x.strip() for x in args.target_regions.split(",") if x.strip()]
    masks = []
    for idx, region in enumerate(regions, start=1):
        masks.append({
            "mask_id": f"mask_{region}_{idx:02d}",
            "character_id": args.character_id,
            "owner_instance_id": args.instance_id,
            "region_id": region,
            "mask_scale": "major",
            "artifact_path": f"masks/{args.character_id}_{region}.png",
            "sha256": "REPLACE_WITH_MASK_SHA256",
            "feather_px": args.feather_px,
            "dilation_px": args.dilation_px,
            "blur_px": args.blur_px,
            "protected_exclusions": ["face_identity", "hands_contact_exclusion", "background"],
            "priority_order": idx,
        })
    pass_plan = [{
        "pass_id": "body_shape_pass_001",
        "pass_type": args.pass_type,
        "engine_family": args.engine_family,
        "input_image": args.source_image,
        "output_prefix": f"Main_Flow/Body_Shape_Correction/{args.character_id}/{args.pass_type}",
        "masks": [m["mask_id"] for m in masks],
        "denoise": args.denoise,
        "steps": args.steps,
        "cfg": args.cfg,
        "same_engine_loras": [],
        "forbidden_changes": ["face_identity", "pose", "camera_crop", "background", "character_count"],
        "qa_required": True,
    }]
    qa_goals = [
        {"goal_id": "qa_identity", "metric_id": "identity_preservation", "threshold": 0.90, "weight": 0.16, "required": True, "auto_fail_if_missing": True},
        {"goal_id": "qa_pose", "metric_id": "pose_preservation", "threshold": 0.86, "weight": 0.12, "required": True, "auto_fail_if_missing": True},
        {"goal_id": "qa_target", "metric_id": "target_region_improvement", "threshold": 0.80, "weight": 0.16, "required": True, "auto_fail_if_missing": True},
        {"goal_id": "qa_blend", "metric_id": "mask_edge_blend", "threshold": 0.82, "weight": 0.08, "required": True, "auto_fail_if_missing": True},
    ]
    return {
        "contract_id": args.contract_id,
        "scene_id": args.scene_id,
        "character_id": args.character_id,
        "character_version": args.character_version,
        "source_image": {"path_or_artifact_id": args.source_image, "sha256": source_hash},
        "target_profile": args.target_profile,
        "target_regions": regions,
        "protected_regions": ["face_identity", "hands_contact_exclusion", "background"],
        "mask_plan": masks,
        "pass_plan": pass_plan,
        "qa_goals": qa_goals,
        "promotion_policy": {"requires_qa_pass": True, "allows_global_redraw": False, "max_total_reruns": args.max_reruns},
        "notes": ["Generated by compile_body_shape_correction_contract.py"],
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--contract-id", default="body_shape_contract_001")
    parser.add_argument("--scene-id", default="scene_001")
    parser.add_argument("--character-id", required=True)
    parser.add_argument("--character-version", default="v001")
    parser.add_argument("--instance-id", default="person_001")
    parser.add_argument("--source-image", required=True)
    parser.add_argument("--source-sha256", default="")
    parser.add_argument("--target-profile", default="subtle_waist_stomach_refine")
    parser.add_argument("--target-regions", default="abdomen_stomach,waist_left,waist_right,outer_silhouette")
    parser.add_argument("--pass-type", default="stomach_refine")
    parser.add_argument("--engine-family", default="sdxl")
    parser.add_argument("--denoise", type=float, default=0.22)
    parser.add_argument("--steps", type=int, default=14)
    parser.add_argument("--cfg", type=float, default=5.0)
    parser.add_argument("--feather-px", type=int, default=48)
    parser.add_argument("--dilation-px", type=int, default=10)
    parser.add_argument("--blur-px", type=int, default=12)
    parser.add_argument("--max-reruns", type=int, default=4)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    contract = build_contract(args)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(contract, indent=2), encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
